name: build-playground/build-playground_(21)
on:
  push:
    branches:
    - "*"
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - run: echo We are now calling template_jobs

  templates_jobs:
    name: templates_jobs
    uses: begonaguereca/importer/.github/workflows/templates_jobs.yml@main

  third:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - run: echo We are now calling the template steps
    - uses: begonaguereca/importer/.github/actions/templates_step@main
