name: build-playground/build-playground_(21)
on:
  push:
    branches:
    - "*"
jobs:
  templates_jobs:
    name: templates_jobs
    uses: begonaguereca/importer/.github/workflows/templates_jobs.yml@main
  alt:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - run: echo This script runs before the template steps.
    - uses: begonaguereca/importer/.github/actions/templates_step@main
    - run: echo This step runs after the template steps.
