name: build-playground/build-playground_(21)
on:
  push:
    branches:
    - "*"
jobs:
  templates_jobs:
    name: templates_jobs
    uses: "./.github/workflows/templates_jobs.yml"
  alt:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - run: echo This script runs before the template's steps.
    - uses: "./.github/actions/templates_step"
    - run: echo This step runs after the template's steps.
