name: build-playground/begonaguereca/demo
on:
  push:
    branches:
    - main
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
#     # This item has no matching transformer
#     - task: GoTool@0
#       inputs:
#         version: '1.10'
