name: build-playground/demo-build-pipeline
on:
  push:
    branches:
    - main
jobs:
  Job:
    runs-on:
      - mechamachine
      - X86
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.10'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "${{ env.branch == 'refs/heads/main' || startsWith(env.branch, 'refs/heads/releases/') }}"
        password: "${{ secrets.MY_OWN_DOCKER_HUB_ACCESS_TOKEN }}"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: "**/Dockerfile"
        push: true
